version: '3'
services:
    db:
        image: docker.io/library/postgres:latest
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/db_data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1Qwertytrewq
            - POSTGRES_DBNAME=app
        build:
            context: ./db

    rust_api:
        image: docker.io/library/rust:latest
        container_name: rust_api
        build:
            context: ./axum_api
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - db

volumes:
    db_data: {}
